# GitHub Pages Configuration
title: "Pelatihan Google Earth Engine"
description: "Panduan penggunaan Google Earth Engine untuk pemantauan upwelling"
theme: jekyll-theme-minimal

# Set the base URL and source directory
baseurl: "/BUDEE"
url: "https://manessa-md.github.io"
source: "docs"

# Sidebar Navigation
include: ["_sidebar.md"]

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github/
  - .gitignore
